// Code generated by "stringer -type=Choice"; DO NOT EDIT.

package blackjack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hit-1]
	_ = x[Stand-2]
}

const _Choice_name = "hitstand"

var _Choice_index = [...]uint8{0, 3, 8}

func (i Choice) String() string {
	i -= 1
	if i >= Choice(len(_Choice_index)-1) {
		return "Choice(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Choice_name[_Choice_index[i]:_Choice_index[i+1]]
}
